"""Prepare beers.json, generated by the crawler, for insertion into ES."""
import argparse
import json
import os
import re

from dateutil import parser as date_parser


def read_options_and_run():
    """Read the options passed in from console and parse the beers."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "beers", help="Path to the beers.json generated by the crawler")
    args = parser.parse_args()
    if not os.path.isfile(args.beers):
        raise ValueError("You must supply a path to the beers.json file")

    process_file(args.beers)


def process_file(fname):
    with open(fname, 'r') as beers:
        for beer in beers:
            process_beer(json.loads(beer))


def strip_word(word):
    word = word.replace("-", " ")
    word = word.replace("'s", '')
    return re.sub(r"[^\w ]", '', word).strip()


def process_beer(beer):
    """Process an individual beer JSON object."""
    # Make sure the timestamp is formatted correctly
    beer['timestamp'] = date_parser.parse(beer['timestamp']).isoformat()

    # remove all brewery words from beer name
    brewery_name_words = strip_word(beer['brewery']).lower().split(' ')
    beer_name = strip_word(beer['name']).lower()
    for brewery_word in brewery_name_words:
        beer_name = beer_name.replace(brewery_word, '')
    beer['name_no_brewery'] = re.sub(r'\s+', ' ', beer_name).strip()

    # Note! If you don't encode as utf8, then redirecting stdout throws
    # a UnicodeEncodeError!
    print(json.dumps(beer, ensure_ascii=False).encode('utf8'))


if __name__ == "__main__":
    read_options_and_run()
